FROM quay.io/maherzubair/sigma-md:beta
RUN git clone https://github.com/Sithuwa/SITHU-MD /root/Temitopeareo/ABROMD1
WORKDIR /root/Temitopeareo/ABROMD1/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
